#!/usr/bin/env python3
"""Refresh the bundled model price snapshot from LiteLLM's public price list.

Usage: scripts/update-prices.py [path-or-url]
Writes Sources/UsageBar/Support/BundledModelPrices.swift. Only chat models with an input and
output price are kept, and only the fields UsageBar reads. Keys with a provider path prefix
(e.g. "openrouter/anthropic/claude-opus-5") are kept under their base name when no first-party
entry with that name exists, so OpenCode model IDs from other gateways still match.
"""
import json, sys, datetime, urllib.request, pathlib

SOURCE = "https://raw.githubusercontent.com/BerriAI/litellm/refs/heads/main/model_prices_and_context_window.json"
FIELDS = ["input_cost_per_token", "output_cost_per_token", "cache_read_input_token_cost",
          "cache_creation_input_token_cost", "litellm_provider"]

def load(arg):
    if arg and not arg.startswith("http"):
        return json.load(open(arg))
    with urllib.request.urlopen(arg or SOURCE, timeout=60) as r:
        return json.load(r)

def main():
    raw = load(sys.argv[1] if len(sys.argv) > 1 else None)
    keep = {}
    # First pass: keys without a path prefix win. Second pass: prefixed keys fill gaps by base name.
    for prefixed in (False, True):
        for key, v in raw.items():
            if key == "sample_spec" or not isinstance(v, dict): continue
            if ("/" in key) != prefixed: continue
            if v.get("mode") not in ("chat", "responses"): continue
            if "input_cost_per_token" not in v or "output_cost_per_token" not in v: continue
            name = key.rsplit("/", 1)[-1].lower()
            if name in keep: continue
            keep[name] = {f: v[f] for f in FIELDS if f in v}
    payload = {"source": SOURCE, "updated": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
               "models": keep}
    body = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    out = pathlib.Path(__file__).resolve().parent.parent / "Sources/UsageBar/Support/BundledModelPrices.swift"
    out.write_text(f'''// Generated by scripts/update-prices.py on {payload["updated"]} from LiteLLM. Do not edit by hand.
// {len(keep)} chat models · prices in USD per token · source: {SOURCE}
enum BundledModelPrices {{
    static let json = #"""
{body}
"""#
}}
''')
    print(f"wrote {out} with {len(keep)} models")

if __name__ == "__main__":
    main()
